#!/usr/bin/env python3
"""
ZX Showcase - Procedural Asset Generation Runner

Usage:
    python run.py --game neon-drift --all
    python run.py --game prism-survivors --asset hero_knight
    python run.py --game lumina-depths --asset jellyfish --preview
"""

import argparse
import json
import os
import sys
from pathlib import Path

# Add procgen to path
PROCGEN_ROOT = Path(__file__).parent
sys.path.insert(0, str(PROCGEN_ROOT.parent))

from procgen.core import UniversalStyleParams
from procgen.configs import get_style_tokens
from procgen.meshes import (
    generate_humanoid, generate_vehicle, generate_crystal,
    generate_creature, generate_prop, MeshData
)
from procgen.textures import (
    generate_albedo, generate_emission, generate_roughness,
    generate_neon_glow, generate_bioluminescence, generate_prismatic_glow,
)


def get_output_dir(game_name: str) -> Path:
    """Get output directory for generated assets."""
    showcase_root = PROCGEN_ROOT.parent
    output_dir = showcase_root / "games" / game_name.replace("-", "_").replace("_", "-") / "assets" / "generated"
    output_dir.mkdir(parents=True, exist_ok=True)
    return output_dir


def export_mesh_obj(mesh: MeshData, filepath: Path):
    """Export mesh to OBJ format."""
    with open(filepath, "w") as f:
        f.write(f"# Generated by ZX Showcase Procgen\n")
        f.write(f"# Triangles: {mesh.triangle_count}\n\n")

        # Vertices
        for x, y, z in mesh.vertices:
            f.write(f"v {x:.6f} {y:.6f} {z:.6f}\n")

        f.write("\n")

        # Faces (OBJ is 1-indexed)
        for face in mesh.faces:
            indices = " ".join(str(v + 1) for v in face)
            f.write(f"f {indices}\n")

    print(f"Exported: {filepath} ({mesh.triangle_count} tris)")


def export_texture_ppm(texture, filepath: Path):
    """Export texture to PPM format (simple, no dependencies)."""
    with open(filepath, "wb") as f:
        f.write(f"P6\n{texture.width} {texture.height}\n255\n".encode())
        for row in texture.pixels:
            for r, g, b, a in row:
                f.write(bytes([r, g, b]))

    print(f"Exported: {filepath} ({texture.width}x{texture.height})")


def generate_neon_drift_assets(style: UniversalStyleParams, output_dir: Path, preview: bool = False):
    """Generate all assets for Neon Drift."""
    print("\n=== Generating Neon Drift Assets ===")

    from procgen.configs.neon_drift import CAR_PRESETS, TRACK_PRESETS

    # Generate cars
    print("\n--- Vehicles ---")
    for car_name, preset in CAR_PRESETS.items():
        mesh = generate_vehicle(style, preset=preset, vehicle_type=car_name)
        export_mesh_obj(mesh, output_dir / f"car_{car_name}.obj")

        # Generate car textures
        color = preset.get("color_primary", "#00FFFF")
        if color.startswith("#"):
            from procgen.textures.pbr_textures import hex_to_rgb
            rgb = hex_to_rgb(color)
        else:
            rgb = (0, 255, 255)

        albedo = generate_albedo(style, base_color=rgb, pattern="metallic")
        export_texture_ppm(albedo, output_dir / f"car_{car_name}_albedo.ppm")

        emission = generate_neon_glow(color=rgb, pattern="strips")
        export_texture_ppm(emission, output_dir / f"car_{car_name}_emission.ppm")

    # Generate track pieces
    print("\n--- Track Segments ---")
    from procgen.meshes.environment import generate_track_segment, generate_checkpoint_gate

    straight = generate_track_segment(style, segment_type="straight")
    export_mesh_obj(straight, output_dir / "track_straight.obj")

    checkpoint = generate_checkpoint_gate(style)
    export_mesh_obj(checkpoint, output_dir / "track_checkpoint.obj")

    # Generate track textures (grid)
    from procgen.textures.noise_patterns import generate_hexagon_grid
    grid = generate_hexagon_grid(hex_size=32, line_color=(0, 217, 255), bg_color=(10, 15, 25))
    export_texture_ppm(grid, output_dir / "track_grid.ppm")

    print(f"\nNeon Drift assets generated in: {output_dir}")


def generate_lumina_depths_assets(style: UniversalStyleParams, output_dir: Path, preview: bool = False):
    """Generate all assets for Lumina Depths."""
    print("\n=== Generating Lumina Depths Assets ===")

    from procgen.configs.lumina_depths import CREATURE_PRESETS, ENVIRONMENT_PRESETS

    # Generate creatures
    print("\n--- Creatures ---")
    for creature_name, preset in CREATURE_PRESETS.items():
        creature_type = preset.get("body_type", "jellyfish").split("_")[0]
        if creature_type in ("bell", "jellyfish"):
            creature_type = "jellyfish"
        elif creature_type in ("eel", "elongated"):
            creature_type = "eel"
        elif creature_type in ("angular", "predator"):
            creature_type = "predator"
        else:
            creature_type = "fish"

        # Create preset dict for generator
        gen_preset = {
            "scale": preset.get("scale_range", (1.0, 1.0))[0] if isinstance(preset.get("scale_range"), tuple) else 1.0,
            "limb_count": preset.get("limb_count", 8),
        }

        mesh = generate_creature(style, preset=gen_preset, creature_type=creature_type)
        export_mesh_obj(mesh, output_dir / f"creature_{creature_name}.obj")

        # Bioluminescent texture
        color_hex = preset.get("color_glow", "#00FFCC")
        from procgen.textures.pbr_textures import hex_to_rgb
        glow_color = hex_to_rgb(color_hex)

        bio_glow = generate_bioluminescence(
            color_primary=glow_color,
            color_secondary=(100, 180, 255),
            spot_count=8,
        )
        export_texture_ppm(bio_glow, output_dir / f"creature_{creature_name}_emission.ppm")

    # Generate environment
    print("\n--- Environment ---")
    from procgen.meshes.creatures import generate_coral

    for coral_type in ["branching", "brain", "fan"]:
        coral = generate_coral(style, coral_type=coral_type)
        export_mesh_obj(coral, output_dir / f"coral_{coral_type}.obj")

    print(f"\nLumina Depths assets generated in: {output_dir}")


def generate_prism_survivors_assets(style: UniversalStyleParams, output_dir: Path, preview: bool = False):
    """Generate all assets for Prism Survivors."""
    print("\n=== Generating Prism Survivors Assets ===")

    from procgen.configs.prism_survivors import HERO_PRESETS, ENEMY_PRESETS

    # Generate heroes
    print("\n--- Heroes ---")
    for hero_name, preset in HERO_PRESETS.items():
        mesh = generate_humanoid(style, preset=preset, size_class="medium")
        export_mesh_obj(mesh, output_dir / f"hero_{hero_name}.obj")

        # Generate hero textures
        color = preset.get("color_primary", [0.5, 0.5, 0.5])
        rgb = tuple(int(c * 255) for c in color)

        albedo = generate_albedo(style, base_color=rgb, pattern="noisy")
        export_texture_ppm(albedo, output_dir / f"hero_{hero_name}_albedo.ppm")

        accent = preset.get("color_accent", [1.0, 1.0, 1.0])
        accent_rgb = tuple(int(c * 255) for c in accent)
        emission = generate_emission(style, emission_color=accent_rgb, pattern="outline")
        export_texture_ppm(emission, output_dir / f"hero_{hero_name}_emission.ppm")

    # Generate enemies
    print("\n--- Enemies ---")
    from procgen.meshes.humanoid import generate_enemy

    for enemy_name, preset in ENEMY_PRESETS.items():
        tier = preset.get("tier", "basic")
        mesh = generate_enemy(style, preset=preset, tier=tier)
        export_mesh_obj(mesh, output_dir / f"enemy_{enemy_name}.obj")

        # Enemy glow
        glow_color = preset.get("color_glow", [0.5, 0.5, 0.5])
        glow_rgb = tuple(int(c * 255) for c in glow_color)
        glow = generate_prismatic_glow(pattern="facets", brightness=0.8)
        export_texture_ppm(glow, output_dir / f"enemy_{enemy_name}_emission.ppm")

    # Generate pickups
    print("\n--- Pickups ---")
    from procgen.meshes.crystals import generate_xp_gem, generate_projectile
    from procgen.meshes.environment import generate_health_pickup, generate_powerup

    xp_gem = generate_xp_gem(size=0.2)
    export_mesh_obj(xp_gem, output_dir / "pickup_xp_gem.obj")

    health = generate_health_pickup(size=0.3)
    export_mesh_obj(health, output_dir / "pickup_health.obj")

    for ptype in ["speed", "shield", "weapon"]:
        powerup = generate_powerup(powerup_type=ptype)
        export_mesh_obj(powerup, output_dir / f"pickup_{ptype}.obj")

    # Generate projectiles
    print("\n--- Projectiles ---")
    for ptype in ["shard", "orb", "beam"]:
        proj = generate_projectile(projectile_type=ptype)
        export_mesh_obj(proj, output_dir / f"projectile_{ptype}.obj")

    print(f"\nPrism Survivors assets generated in: {output_dir}")


def main():
    parser = argparse.ArgumentParser(description="ZX Showcase Procedural Asset Generator")
    parser.add_argument("--game", required=True, choices=["neon-drift", "lumina-depths", "prism-survivors"],
                        help="Target game")
    parser.add_argument("--asset", type=str, help="Specific asset to generate (or 'all')")
    parser.add_argument("--all", action="store_true", help="Generate all assets")
    parser.add_argument("--preview", action="store_true", help="Open in Blender for preview")
    parser.add_argument("--output", type=str, help="Custom output directory")

    args = parser.parse_args()

    # Get style tokens for game
    style = get_style_tokens(args.game)
    if style is None:
        print(f"Error: No style tokens found for game '{args.game}'")
        sys.exit(1)

    # Get output directory
    if args.output:
        output_dir = Path(args.output)
        output_dir.mkdir(parents=True, exist_ok=True)
    else:
        output_dir = get_output_dir(args.game)

    print(f"Game: {args.game}")
    print(f"Style: {style.style_name}")
    print(f"Output: {output_dir}")

    # Generate assets
    if args.all or args.asset == "all":
        if args.game == "neon-drift":
            generate_neon_drift_assets(style, output_dir, args.preview)
        elif args.game == "lumina-depths":
            generate_lumina_depths_assets(style, output_dir, args.preview)
        elif args.game == "prism-survivors":
            generate_prism_survivors_assets(style, output_dir, args.preview)
    elif args.asset:
        print(f"Generating specific asset: {args.asset}")
        # TODO: Implement single asset generation
        print("Single asset generation not yet implemented. Use --all")
    else:
        parser.print_help()


if __name__ == "__main__":
    main()
